In [5]:
import numpy as np

## Creating Numpy Arrays

In [7]:
oneDArray = np.array([1, 2, 3, 4, 5])
print(oneDArray)

[1 2 3 4 5]


In [9]:
print(oneDArray.ndim)

1


In [12]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
print(twoDArray)

[[1 2 3]
 [4 5 6]]


In [13]:
twoDArray.ndim

2

In [15]:
threeDArray = np.array([[[1, 2, 3], [-1, -2, -3]], [[4, 5, 6], [-4, -5, -6]]])
print(threeDArray)
threeDArray.ndim

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]]


3