In [1]:
import numpy as np

## Indexing Numpy Arrays

In [9]:
twoDArray = np.array([[1, 2, 3], [4, 5, 6]])
twoDArray[1, 2]

6

In [10]:
threeDArray = np.array([[[1, 2, 3], [-1, -2, -3]], 
                        [[4, 5, 6], [-4, -5, -6]], 
                        [[7, 8, 9], [-7, -8, -9]]])
print(threeDArray)
print(threeDArray.ndim)
threeDArray[2, 1, 0]

[[[ 1  2  3]
  [-1 -2 -3]]

 [[ 4  5  6]
  [-4 -5 -6]]

 [[ 7  8  9]
  [-7 -8 -9]]]
3


-7