## Mathematics for Data Science

In [2]:
import numpy as np

In [3]:
# zeros
zerosArray = np.zeros(10)
print(zerosArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
zerosArray = zerosArray.astype(int)
print(zerosArray)

[0 0 0 0 0 0 0 0 0 0]


In [11]:
# ones
onesArray = np.ones(10)
# onesArray.shape = (2, 5)
print(onesArray)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
# full
filledArray = np.full(10, 5)
print(filledArray)

[5 5 5 5 5 5 5 5 5 5]


In [15]:
# Adding a scalar
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix + 2)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [16]:
# Subtracting a scalar
print(matrix - 2)

[[-1  0  1]
 [ 2  3  4]]


In [20]:
# Multiplying by a scalar
print(matrix * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [21]:
# Dividing by a scalar
print(matrix / 2)
print(matrix // 2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]
[[0 1 1]
 [2 2 3]]


In [23]:
# Raising to a power
print(matrix ** 2)

[[ 1  4  9]
 [16 25 36]]


In [25]:
# Transposing an array
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]


## Element-wise operations

In [28]:
# Addition
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[-1, -2, -3], [-4, -5, -6]])

print(matrix1 + matrix2)

[[0 0 0]
 [0 0 0]]


In [29]:
# Subtraction
print(matrix1 - matrix2)

[[ 2  4  6]
 [ 8 10 12]]


In [30]:
# Multiplication
print(matrix1 * matrix2)

[[ -1  -4  -9]
 [-16 -25 -36]]


In [31]:
# Division
print(matrix1 / matrix2)

[[-1. -1. -1.]
 [-1. -1. -1.]]


In [32]:
# Division
print(matrix1 // matrix2)

[[-1 -1 -1]
 [-1 -1 -1]]


## Matrix Multiplication

In [34]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
print(matrix_a)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [35]:
matrix_b = np.array([[-1, -2, -3], [-4, -5, -6], [0, 0, 0]])
print(matrix_b)

[[-1 -2 -3]
 [-4 -5 -6]
 [ 0  0  0]]


In [36]:
print(np.matmul(matrix_a, matrix_b))

[[ -9 -12 -15]
 [-24 -33 -42]
 [  0   0   0]]


## Statistics

In [39]:
# min
matrix_x = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix_x.min())

1


In [41]:
# max
print(matrix_x.max())

6


In [44]:
# sum
print(matrix_x.sum())

21


In [46]:
# mean
print(matrix_x.mean())

3.5


In [49]:
# median
print(np.median(matrix_x))

3.5


In [43]:
# std
print(matrix_x.std())

1.707825127659933
